### ISSUE TITLE
Add Vienna (France)

### ISSUE THREAD

**Issue by Msch0150** [nomisma/data#12]
Could you add the mint "Vienna"?
There was a mint in Vienne in France. The acient name was "Vienna" (unfortunately the same name as the capital of Austria).
A. Burnett, M. Amandry, P. P. Ripollès: Roman Provincial Coinage, Volume I, Part I, 151:
Vienna
The coinage signed C.I.V. is well known and very abundant. It was struck at Colonia Iulia Viennensis, where a colony with ius Latinum was founded in c. 50 BC. ...

**Comment by Msch0150** [comment]
Same for:
Apta Iulia (RPC page 150),
Cabellio (RPC page 154),
Antipolis (RPC page 154),
Arausio (RPC page 155),
Forum Iulii (RPC page 155),

**Comment by ewg118** [comment]
I'll forward these to David Wigg-Wolf, who can create them as soon as the new Nomisma data provenance model is moved into production.

**Comment by Msch0150** [comment]
Is there any new information on this topic?

**Comment by ewg118** [comment]
I emailed David again. Will update soon.

**Comment by Msch0150** [comment]
I can see "Vienne" now, thanks.
(http://nomisma.org/id/colonia_iulia_viennensis)
There is a small copy/paste issue for the Longitude (which is the same as the Latitude). It mentions 45.52569,
but it should be something like 4.8781 (https://en.wikipedia.org/wiki/Vienne,_Is%C3%A8re).


(http://nomisma.org/id/forum-iulii)
I looks like that for "Forum Iulii" the coordinates of the italian "Forum Iulii" had been used. But it should be the french "Forum Iulii", see https://en.wikipedia.org/wiki/Forum_Iulii | https://en.wikipedia.org/wiki/Cividale_del_Friuli.


The other cities look quite fine. Thanks a lot.

**Comment by ewg118** [comment]
I fixed the coordinates of Vienne. I also fixed the coordinates of Forum Iulii and replaced the Pleiades URI with the correct one, as it also pointed to the town in Italy.

**Comment by Msch0150** [comment]
Looks fine. Thanks!
