### ISSUE TITLE
Insert dcterms namespace into ontology

### ISSUE THREAD

**Issue by ewg118** [nomisma/data#17]
Since we link a few classes in our ontology to superclasses in dcterms, can you update the ontologies to add prefix/namespace for dcterms / http://purl.org/dc/terms/ ? This will help me in a new version of the ontology HTML page that looks more like W3C pages.

**Comment by karstenT** [comment]
Sure, will work on it! 

Am 11.11.2019 14:58, schrieb Ethan Gruber:

> Since we link a few classes in our ontology to superclasses in dcterms, can you update the ontologies to add prefix/namespace for dcterms / http://purl.org/dc/terms/ ? This will help me in a new version of the ontology HTML page that looks more like W3C pages. 
> 
> --
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/nomisma/data/issues/17?email_source=notifications&amp;email_token=ACQPQHVPVM4N3RHGJSDWZTDQTFQKFA5CNFSM4JLV5PI2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HYNQJWQ
[2]

**Comment by karstenT** [comment]
Hi Ethan, 

I included the prefixes/namespaces: dcterms, crm and dcmitype 

... and also added a dcterms:date statement. 

Pull request ist out. 

Best 

Karsten

Am 11.11.2019 14:58, schrieb Ethan Gruber:

> Since we link a few classes in our ontology to superclasses in dcterms, can you update the ontologies to add prefix/namespace for dcterms / http://purl.org/dc/terms/ ? This will help me in a new version of the ontology HTML page that looks more like W3C pages. 
> 
> --
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/nomisma/data/issues/17?email_source=notifications&amp;email_token=ACQPQHVPVM4N3RHGJSDWZTDQTFQKFA5CNFSM4JLV5PI2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HYNQJWQ
[2]
